### ISSUE TITLE
CUDA build fails to run Insert.NullArrayNullEmpty test with LLVM-12 and ORCJIT

### ISSUE THREAD

**Issue by kurapov-peter** [intel-ai/omniscidb#446]
Running default config tests result in a SIGSEGV:
```
conda update conda
env update -f scripts/mapd-deps-conda-dev-env.yml
conda install -c conda-forge cudatoolkit-dev arrow-cpp-proc=3.0.0=cuda
bash scripts/conda/build-install-all.sh
cd build && ccmake . # change ENABLE_CUDA=on and ENABLE_TESTS=ON
cmake --build . 
cd Tests && ./ArrowBasedExecuteTest --gtest_filter=Insert.NullArrayNullEmpty

```
Results in:
```
#0  0x00007fffefbedb7d in llvm::LLVMTargetMachine::initAsmInfo() () from /miniconda3/envs/omnisci-dev/lib/libLLVM-12.so
#1  0x00007ffff2274d4c in llvm::NVPTXTargetMachine::NVPTXTargetMachine(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, llvm::Optional<llvm::CodeModel::Model>, llvm::CodeGenOpt::Level, bool) ()
   from /miniconda3/envs/omnisci-dev/lib/libLLVM-12.so
#2  0x00007ffff2275052 in llvm::RegisterTargetMachine<llvm::NVPTXTargetMachine64>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, llvm::Optional<llvm::CodeModel::Model>, llvm::CodeGenOpt::Level, bool) ()
   from /miniconda3/envs/omnisci-dev/lib/libLLVM-12.so
#3  0x0000555555d39dde in llvm::Target::createTargetMachine (JIT=false, OL=llvm::CodeGenOpt::Default, CM=..., RM=..., Options=..., Features=..., CPU=..., TT=..., this=0x7ffff4fdafa0 <llvm::getTheNVPTXTarget64()::TheNVPTXTarget64>) at /miniconda3/envs/omnisci-dev/include/llvm/ADT/Twine.h:289
#4  CodeGenerator::initializeNVPTXBackend (arch=<optimized out>) at /omniscidb/QueryEngine/NativeCodegen.cpp:1462
...
```

Seems like `NVPTXTargetMachine` calls `LLVMTargetMachine::initAsmInfo` (https://llvm.org/doxygen/LLVMTargetMachine_8cpp_source.html#l00040) unconditionally in the constructor. With MC targets uninitialized all the calls inside `initAsmInfo` return nullptrs and should result in a SIGSEGV.

I might have disabled ORCJIT while working on GPUs previously, so I wonder if it ever worked with CUDA enabled.

Adding `llvm::InitializeAllTargetMCs()` fixes the issue for me.

**Comment by kurapov-peter** [comment]
> I might have disabled ORCJIT while working on GPUs previously, so I wonder if it ever worked with CUDA enabled.

Indeed, MCJIT was the default until recently ff13dc919b71d76d721a85c0ba3b060ff8be4e68.
